### ISSUE TITLE
Identifying Crew Members

### ISSUE THREAD

**Issue by zappybiby** [ajchili/BomberCrewBot#1]
Under `%APPDATA%\..\LocalLow\Runner Duck\Bomber Crew` ... find file `BC_SaveSlotV2_0.dat` and open it with Notepad++

The roles of the active crew members can be found under "m_activeCrewmen" -> "m_primarySkill":

```
Pilot - "m_skillType": 0
Gunner - "m_skillType": 1
Navigator - "m_skillType": 2
Radio Op - "m_skillType": 3
Engineer - "m_skillType": 4
Bomber - "m_skillType": 5
```
What we need to do:
- [x] Get BomberCrewBot to navigate to `%APPDATA%\..\LocalLow\Runner Duck\Bomber Crew`
- [x] Think of a way to read this save file starting from "m_activeCrewmen"
- [x] Create a class for crew memebers that we can add traits to.
  - Define pilot, gunner, navigator, radio op, engineer, and bomber as skills in our program
- [x] Make sure that our program labels each active crew member sequentially. This would mean that the first crew member under "m_activeCrewman" would be labeled as 'crew member 1'. 
  - This will be important later on when we need the bot to select a specific member of the crew.'

Considerations:
- We should be reading this every time the program is started to make sure we account for changes in crew structure.
- What if some of the crew is lost after a mission? We might need to read the save file on a set interval.

**Comment by ajchili** [comment]
@zappybiby We can read the file on key press, that way a user can determine when it is best to refresh crew members.

**Comment by ajchili** [comment]
Once I get home I can take care of 1 and 2.
