### ISSUE TITLE
detecting enemy planes

### ISSUE THREAD

**Issue by zappybiby** [ajchili/BomberCrewBot#14]
See this commit (Literally have no idea how to rebase old experimental branch onto master so I just created a new one): https://github.com/ajchili/BomberCrewBot/commit/1bc43af30705aad1dc8a8d4650470b958a315e82

debating whether to use houghcircles or  match template for this. InRange values are pretty good for night time and shouldn't need to be changed too much.

**Comment by ajchili** [comment]
So you need help merging?

If so you'll be making a Pull Request then make me a reviewer.

**Comment by zappybiby** [comment]
Well no not really I just made a new branch so 

If I am doing it I would rebase because merging would have so many commits

regardless this issue is about the enemy plane spotting and what the honk we are going to

**Comment by ajchili** [comment]
Merging would make it one commit.

**Comment by ajchili** [comment]
Was this issue fixed? If so close the issue.
