### ISSUE TITLE
Identifying Airplane Parts

### ISSUE THREAD

**Issue by zappybiby** [ajchili/BomberCrewBot#2]
The bot should know where to click to access different turrents

I propose the following method to do this:

Have the bot press shift. This way we can establish a consistent overview of the inside of the plane

Relative window:  Coordinates are relative to the active window.
Client window: Coordinates are relative to the active window's client area, which excludes the window's title bar, menu (if it has a standard one) and borders

Using 1600 x 900 resolution windowed.

- Top Turret: 
  - Relative: 685, 352
  - Client: 682, 326

- Rear Turret: 
  - Relative Window: 298, 398
  - Client Window: 295, 372

- Front Turret: 
  - Relative Window: 1403, 372
  - Client Window: 1400, 346

- Bomber Seat:
  - Relative Window: 1420, 478
  - Client Window: 1417, 452

- Pilot Seat
  - Relative Window: 1301, 345
  - Client Window: 1298, 319

- Engineer Seat
  - Relative Window: 1274, 426
  - Client Window: 1271, 400

- Navigation Seat
  - Relative Window: 1192, 407
  - Client Window: 1189, 381

- Radio Op Seat:
  - Relative Window: 1100, 406
  - Client Window: 1097, 380

- Electrical Panel: 
  - Relative Window: 523, 384
  - Client Window: 520, 358

- Hydraulics Panel:
  - Relative Window: 1050, 368
  - Client Window: 1047, 342

- Fuel Panel
  - Relative Window: 1277, 455
  - Client Window: 1274, 429

**Comment by ajchili** [comment]
This has somewhat been done, plan part locations will be clickable as pyautogui has been 'implemented' but #3 needs to be tackled first.
