### ISSUE TITLE
Identifying Icons

### ISSUE THREAD

**Issue by zappybiby** [ajchili/BomberCrewBot#3]
Comparing different ways to find icons. 

Starting with this initial image.
![nav](https://user-images.githubusercontent.com/15076478/32073976-f4f9303c-ba65-11e7-8144-fc9a27e58deb.png)

Thresholding the image at level 169
![thresh169](https://user-images.githubusercontent.com/15076478/32072859-279e377a-ba62-11e7-86b0-43203b7a487b.png)

That seems OK ... if the view is zoomed out,

But, take this example where the view is zoomed in:
![capture](https://user-images.githubusercontent.com/15076478/32073030-af69b40e-ba62-11e7-8bdf-8d22e5b21d3f.PNG)
Attempting to apply a threshold of level 132...
![capture copy](https://user-images.githubusercontent.com/15076478/32073110-ee951dda-ba62-11e7-9d74-5daca76c0888.png)
The Map icon is much smaller at the bottom right and the other objects in the way might throw off our detection of it. 

So... let's try filtering out the color, making everything else that isn't the [sampled color of the navigation icon](https://www.beautycolorcode.com/8C5307) be set to Black. 
![filtered](https://user-images.githubusercontent.com/15076478/32073833-5e8453d4-ba65-11e7-99e8-10c94b33a87a.PNG)

Looks Great! Just to make sure, lets test this on the initial image where everything is zoomed out.
![filtered2](https://user-images.githubusercontent.com/15076478/32073989-015efac8-ba66-11e7-90a2-c01c3d38b987.PNG)

I think we found our solution!

Next would be to use `cv2.matchTemplate() `to match this icon.

**Comment by ajchili** [comment]
Fixed with [this](https://github.com/ajchili/BomberCrewBot/commit/a148935304f9088443b212eef407776cb47c5852) psuh.

**Comment by ajchili** [comment]
Not completely finished, template mapping not fully implemented.
