### ISSUE TITLE
Moving to nav icon

### ISSUE THREAD

**Issue by zappybiby** [ajchili/BomberCrewBot#6]
Having an issue trying to move mouse cursor to the nav icon

Current implementation:

```
rect_centerX = (min_loc[0] + bottom_right[0])/2
rect_centerY = (min_loc[1] + bottom_right[1])/2
pyautogui.press('space')
pyautogui.moveTo(rect_centerX, rect_centerY, duration=0.5)
```

Note that this implementation would have space being continually being pressed. I tried putting this inside a while loop like: 

`while (rect_centerX is not None) or (rect_centerY is not None):`

However I now realize that if the template is not matched, it will still have a rectangle with the top left coordinate of (0,0). Therefore, rect_centerX and rect_centerY would never be a null value.

When the camera is zoomed in (with spacebar), the cursor position is locked to the center of screen. This means that only the movement of the mouse is captured and the actual position of the mouse stays the same.

In practice, trying to use `pyautogui.moveTo()` when zoomed in will result in the cursor being moved but the actual camera location not changing.

**Comment by ajchili** [comment]
I won't have time to look at this until later tonight. Can push what you have to an experimental/testing branch?

**Comment by zappybiby** [comment]
Keyboard inputs work when camera is centered. We will use `pyautogui` to move towards the detected map icon.

Once the map icon is detected, we should draw a rectangle (or circle) around it. Then we should calculate the positions of the center of the screen to the center of the nav icon. 

psuedocode:
```
if rect_x < screen_center:
   # Move Left
   pyautogui.keyDown('left')
   <recalculate positions>
   # Now centered
   pyautogui.keyUp('left')

```
