### ISSUE TITLE
List of HSV Values and Icons

### ISSUE THREAD

**Issue by zappybiby** [ajchili/BomberCrewBot#7]
Will use this as a temporary repository for HSV colors n stuff

## **FORMAT: #HEX - HSV (SCALED FOR OPENCV)**

close_enemy
![close_enemy](https://user-images.githubusercontent.com/15076478/33343195-7a863dc0-d452-11e7-9143-9f9ba124086b.png)
- Ring: #c32826 - (0, 205,195)

distant_target
![distant target](https://user-images.githubusercontent.com/15076478/33343208-82ccc0e4-d452-11e7-8491-9f50066e95b4.png)
- Inner Circle: #8abe99 - (69, 70, 190)
- Outer Ring: #7da881 - (63, 65, 168)

distant_target2
![distant_target2](https://user-images.githubusercontent.com/15076478/33343228-959c7a48-d452-11e7-86ce-e51701832bed.png)

- Inner Circle: #7fe888 - (63, 115, 232)
- Outer Ring: #52e162 - (63, 162, 225)

distant_target3 
![distant_target3](https://user-images.githubusercontent.com/15076478/33343230-985b1afa-d452-11e7-8c07-50f577b4be91.png)

- Inner Circle: #72D76F - (59, 123, 215)
- Outer Ring: #50E960 - (63, 167, 233)

Wrench: 
![wrench](https://user-images.githubusercontent.com/15076478/33343288-bf181828-d452-11e7-8957-b223b0f4002a.png)

- #f8eaea - (0, 14, 248)

day_sky_nav
![day_sky](https://user-images.githubusercontent.com/15076478/33343295-c17ce008-d452-11e7-8da4-adeb1b0522b9.PNG)

- Inner Color: #ae8d3c - (21, 167, 174)

cloudy_sky_nav
![cloudy_sky](https://user-images.githubusercontent.com/15076478/33343298-c498b492-d452-11e7-8bb0-a7e3fdc85c27.png)

- Inner Color: #a07e2d - (21, 183, 160)

dark_sky_nav
![night_sky](https://user-images.githubusercontent.com/15076478/33347503-129de320-d461-11e7-98af-6989e7a61007.png)

- Inner Color: #7f5100 - (19, 255, 127)

marked
![marked](https://user-images.githubusercontent.com/15076478/33343310-d160fbc6-d452-11e7-8c40-9bb105584838.png)

- Inner Color: #ffa200 - (19, 255, 255)

radar_blip: 
![radar_blip](https://user-images.githubusercontent.com/15076478/33343314-d4c0e1c8-d452-11e7-86de-e0f9579cd566.png)

- Enemy Spotted: #73f644 - (52, 185, 246)
  - Notes: Scan for this color, when detected press shift to align plane to 0 degrees. From that state, the direction in which the camera needs to face to find enemys can be determined. May be needed for night missions.

**Comment by ajchili** [comment]
Hot mama 😍
